language: android
language: node_js
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used
    - build-tools-28.0.3

    # The SDK version used to compile
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jobs:
  include:
    - stage: Build
      script: "export PATH=/usr/local/android-sdk/tools/bin:$PATH && ./gradlew build connectedCheck"
    - stage: GitHub Release
      if: branch = master
      script: npm run release